name: Python

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade setuptools pip wheel
          python -m pip install .[dev]

      - name: Check pep8
        run: |
          flake8 --statistics

      - name: Check pep257
        run: |
          pep257 semaphore

      - name: Check static typing
        run: |
          mypy semaphore examples

      - name: Build package
        run: |
          python -m pip install .
          python setup.py sdist bdist_wheel

      - name: Install package
        run: |
          python -m pip install dist/semaphore-*.tar.gz

      - name: Build documentation
        run: |
          cd docs
          make html
